package com.clickdebit.paysec.connector.constant;

public enum ConnectorServiceConstant {

	TRANSACTION_ID("TRANSACTION_ID"), 
	ORDER_REFERENCE_NUMBER("ORDER_REFERENCE_NUMBER"),
	CART_ID("CART_ID"),
	STATUS("STATUS"),
	QUERY_STATUS("QUERY_STATUS"),
	CALLBACK_STATUS("CALLBACK_STATUS"),
	AMOUNT("AMOUNT"),
	MERCHANT_CODE("MERCHANT_CODE"),
	MERCHANT_KEY("MERCHANT_KEY"),
	MID_ID("MID_ID"),
	MID_KEY("MID_KEY"),
	MID_PRIVATE_KEY("MID_PRIVATE_KEY"),
	MID_PUBLIC_KEY("MID_PUBLIC_KEY"),
	CURRENCY("CURRENCY"),
	BANK_CODE("BANK_CODE"),
	TOKEN("TOKEN"),
	QR_CODE("QR_CODE"),
	RETURN_URL("RETURN_URL"),
	CALLBACK_URL("CALLBACK_URL"),
	
	FIRSTNAME("FIRSTNAME"),
	LASTNAME("LASTNAME"),
	BILLING_EMAIL("BILLING_EMAIL"),
	BILLING_STREET("BILLING_STREET"),
	BILLING_CITY("BILLING_CITY"),
	BILLING_STATE("BILLING_STATE"),
	BILLING_POST_CODE("BILLING_POST_CODE"),
	BILLING_COUNTRY("BILLING_COUNTRY"),
	BILLING_PHONE("BILLING_PHONE"),
	
	URL("URL"),
	TIMEOUT("TIMEOUT"),
	CALLBACK_RESPONSE("CALLBACK_RESPONSE"),
	
	SIGNATURE_CLASS_NAME("SIGNATURE_CLASS_NAME"),
	;

	private String name;

	private ConnectorServiceConstant(String name) {
	  this.name = name;
	 }

	public String getName() {
		return name;
	}
}
